version: '3'
services:
  dependencias:
    image: mystencil:1.0
    command: npm install
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    command: npm run test
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules
    cap_add:
      - SYS_ADMIN
    ports:
      - 4444:3333
      
  app:
    image: mystencil:1.0
    command: npm run start
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules
    ports:
      - "3333:3333"

  build:
    image: mystencil:1.0
    command: npm run build
    volumes:
      - .:/usr/app/

  publish:
    image: mystencil:1.0
    command: npm publish
    volumes:
      - .:/usr/app/